#!/usr/bin/env bats
# Tests for zsh/migrations/20260908-rename-model-env-vars.sh — renames the
# ANTHROPIC_* model env vars to generic AI_* names in ~/.env.local.
bats_require_minimum_version 1.5.0

setup() {
  load 'test_helper'
  common_setup
  MIGRATION="$REPO_ROOT/zsh/migrations/20260908-rename-model-env-vars.sh"
  TMPDIR="$(mktemp -d)"
  ENV_FILE="$TMPDIR/.env.local"
}

teardown() {
  rm -rf "$TMPDIR"
  common_teardown
}

_run_migration() {
  bash -c '
    success() { echo "OK $*"; }
    warn()    { echo "WARN $*"; }
    WORKBENCH_DIR="$2"
    LIB_SRC_DIR="$2/lib"
    LEGACY_WORKBENCH_ROOT="$3/.unused-legacy"
    ENV_LOCAL_FILE="$3/.env.local"
    # output.sh carries sed_i, the portable in-place edit the migration uses.
    # A real sync has it through the ui.sh facade; sourced directly here so
    # the harness exercises the same function rather than a bare `sed -i`.
    . "$WORKBENCH_DIR/lib/output.sh"
    . "$WORKBENCH_DIR/lib/migrations.sh"
    . "$1"
    migration_20260908_rename_model_env_vars
  ' _ "$MIGRATION" "$REPO_ROOT" "$TMPDIR"
}

@test "a machine with no ~/.env.local defers" {
  run _run_migration
  [ "$status" -eq 4 ]
}

@test "renames all four ANTHROPIC_* model vars to AI_*" {
  cat > "$ENV_FILE" << 'EOF'
export COLIMA_CPU=10
export ANTHROPIC_MODEL=claude-opus-5
export ANTHROPIC_DEFAULT_OPUS_MODEL='claude-opus-5'
export ANTHROPIC_DEFAULT_SONNET_MODEL='claude-sonnet-5'
export ANTHROPIC_DEFAULT_HAIKU_MODEL='claude-haiku-4-5@20251001'
EOF

  run _run_migration
  [ "$status" -eq 0 ]
  grep -qx "export AI_MODEL=claude-opus-5" "$ENV_FILE"
  grep -qx "export AI_OPUS_MODEL='claude-opus-5'" "$ENV_FILE"
  grep -qx "export AI_SONNET_MODEL='claude-sonnet-5'" "$ENV_FILE"
  grep -qx "export AI_HAIKU_MODEL='claude-haiku-4-5@20251001'" "$ENV_FILE"
  # Non-model vars are untouched
  grep -qx "export COLIMA_CPU=10" "$ENV_FILE"
  # Old names are gone
  run ! grep -q 'ANTHROPIC_MODEL' "$ENV_FILE"
  run ! grep -q 'ANTHROPIC_DEFAULT' "$ENV_FILE"
}

@test "renames commented-out template lines alongside active exports" {
  cat > "$ENV_FILE" << 'EOF'
export ANTHROPIC_MODEL=claude-opus-5
# export ANTHROPIC_DEFAULT_OPUS_MODEL=
EOF

  run _run_migration
  [ "$status" -eq 0 ]
  grep -qx "export AI_MODEL=claude-opus-5" "$ENV_FILE"
  # The commented template line is renamed in the same sed pass
  grep -qx "# export AI_OPUS_MODEL=" "$ENV_FILE"
}

@test "commented-only lines are still renamed" {
  # The auto-generated section is regenerated by sync, but renaming
  # commented lines avoids confusion if someone reads the file between
  # migration and sync.
  cat > "$ENV_FILE" << 'EOF'
# export ANTHROPIC_MODEL=
EOF

  run _run_migration
  [ "$status" -eq 0 ]
  grep -qx "# export AI_MODEL=" "$ENV_FILE"
}

@test "skips when new name already exists" {
  cat > "$ENV_FILE" << 'EOF'
export ANTHROPIC_MODEL=claude-opus-5
export AI_MODEL=claude-opus-5
EOF

  run _run_migration
  # Old var stays because new already exists — no rename happened
  grep -qx "export ANTHROPIC_MODEL=claude-opus-5" "$ENV_FILE"
  grep -qx "export AI_MODEL=claude-opus-5" "$ENV_FILE"
}

@test "skips when old name is absent" {
  cat > "$ENV_FILE" << 'EOF'
export COLIMA_CPU=10
EOF

  run _run_migration
  # No ANTHROPIC vars to rename — noop
  [ "$status" -eq 3 ]
}

@test "is idempotent" {
  cat > "$ENV_FILE" << 'EOF'
export ANTHROPIC_MODEL=claude-opus-5
export ANTHROPIC_DEFAULT_SONNET_MODEL='claude-sonnet-5'
EOF

  _run_migration
  local first
  first=$(cat "$ENV_FILE")

  run _run_migration
  # Second run: old names are gone, new names already exist — deferred
  [ "$(cat "$ENV_FILE")" = "$first" ]
}

@test "partial rename — only renames vars that exist" {
  cat > "$ENV_FILE" << 'EOF'
export ANTHROPIC_MODEL=claude-opus-5
export ANTHROPIC_DEFAULT_HAIKU_MODEL='claude-haiku-4-5@20251001'
EOF

  run _run_migration
  [ "$status" -eq 0 ]
  grep -qx "export AI_MODEL=claude-opus-5" "$ENV_FILE"
  grep -qx "export AI_HAIKU_MODEL='claude-haiku-4-5@20251001'" "$ENV_FILE"
  # Only 2 lines — nothing else was added
  [ "$(wc -l < "$ENV_FILE")" -eq 2 ]
}
