#!/usr/bin/env bats
# Tests for retro-consume — the deletion at the end of a retro, and the record
# that authorises it.
#
# The incident these guard: `retro-scan --since 1d`, run by hand while
# debugging something unrelated, left a record naming five review directories,
# four of them belonging to branches the retro had nothing to do with. A
# completion run afterwards would have deleted all five. The scan and the
# completion are separate processes with an analysis between them, so the only
# thing that can tie them together is the ID the scan reports and the
# completion quotes back.

bats_require_minimum_version 1.5.0

setup() {
  load 'test_helper'
  common_setup
  RETRO_SCAN="$REPO_ROOT/ai/bin/retro-scan"
  RETRO_CONSUME="$REPO_ROOT/ai/bin/retro-consume"
  RETRO_COMPLETE="$REPO_ROOT/ai/skills/retro/retro-complete.sh"
  sandbox_state_dir
  REVIEWS="$TMPDIR/state/reviews"
  RECORD="$TMPDIR/state/retro-consumed-reviews.json"
  mkdir -p "$REVIEWS"
}

teardown() {
  common_teardown
}

# _make_review NAME [REVIEWED_AT] — a review directory the walk will classify.
_make_review() {
  local name="$1" reviewed_at="${2:-}"
  mkdir -p "$REVIEWS/$name"
  cat > "$REVIEWS/$name/review.md" <<EOF
# Self-Review: otto-nation/$name — branch

## Should fix
- [ ] **[S1]** \`a.py:1\` — something worth saying about tests and mocks
EOF
  if [[ -n "$reviewed_at" ]]; then
    printf '{"reviewed_at": "%s"}\n' "$reviewed_at" > "$REVIEWS/$name/meta.json"
  fi
}

# _make_scannable_home — a home whose registry resolves to one real GitHub
# repo, so a scan runs to completion instead of stopping at the guard that
# refuses a registry resolving to nothing.
_make_scannable_home() {
  mkdir -p "$TMPDIR/home/.claude/machine" "$TMPDIR/repo"
  git -C "$TMPDIR/repo" init -q
  git -C "$TMPDIR/repo" remote add origin git@github.com:otto-nation/myapp.git
  cat > "$TMPDIR/home/.claude/machine/machine.md" <<HEADER
<!-- last-updated: 2026-06-12 | generated by otto-workbench -->
# Machine Profile

## Project Registry

| Project | Path | Stack | Memory |
|---------|------|-------|--------|
| myapp | $TMPDIR/repo | Go | no |
HEADER
}

# _write_record SCAN_ID NAME... — a record claiming NAME... for SCAN_ID.
_write_record() {
  local scan_id="$1"
  shift
  python3 - "$RECORD" "$scan_id" "$@" <<'PY'
import json, sys
path, scan_id, *names = sys.argv[1:]
record = {
    "scan_id": scan_id,
    "scanned_at": "2026-09-17T10:00:00+00:00",
    "reviews": [{"dir_name": n, "repo": "", "reviewed_at": ""} for n in names],
}
with open(path, "w") as f:
    json.dump(record, f)
PY
}

# ── The scan only arms the deletion when asked ──────────────────────────────

@test "a bare scan reads the reviews but writes no consume record" {
  _make_scannable_home
  _make_review "repo-self-branch"

  run "$RETRO_SCAN" --home "$TMPDIR/home" --workbench "$TMPDIR/wb"
  [[ "$status" -eq 0 ]]
  # The scan reached the local reviews — otherwise "no record" would only mean
  # it stopped before the write, which proves nothing about the gate.
  [[ "$output" == *"repo-self-branch"* ]] || [[ "$stderr" == *"local review"* ]]
  [[ ! -f "$RECORD" ]]
  [[ -d "$REVIEWS/repo-self-branch" ]]
}

@test "a --consume scan does write one, and reports its id" {
  _make_scannable_home
  _make_review "repo-self-branch"

  run "$RETRO_SCAN" --home "$TMPDIR/home" --workbench "$TMPDIR/wb" --consume
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"scan-id:"* ]]
  [[ -f "$RECORD" ]]
  grep -q "repo-self-branch" "$RECORD"
}

@test "the reported scan id is the one the record answers to" {
  # The whole handshake in one case: whatever the scan printed must be what
  # the completion has to quote back.
  _make_scannable_home
  _make_review "repo-self-branch"

  run "$RETRO_SCAN" --home "$TMPDIR/home" --workbench "$TMPDIR/wb" --consume
  local scan_id
  scan_id="$(sed -n 's/.*scan-id: \([a-f0-9]*\).*/\1/p' <<< "$output")"
  [[ -n "$scan_id" ]]

  run "$RETRO_CONSUME" --scan-id "$scan_id"
  [[ "$status" -eq 0 ]]
  [[ ! -d "$REVIEWS/repo-self-branch" ]]
}

@test "a second --consume scan displaces the first one's claim" {
  # The abandoned-retro path: a scan that reads nothing still has to overwrite
  # the previous claim, or the abandoned run's list outlives it.
  _make_scannable_home
  _write_record "aaaaaaaaaaaa" "abandoned-run-review"

  run "$RETRO_SCAN" --home "$TMPDIR/home" --workbench "$TMPDIR/wb" --consume
  [[ "$status" -eq 0 ]]
  run grep -c "abandoned-run-review" "$RECORD"
  [[ "$status" -ne 0 ]]
}

@test "--consume with --since is refused" {
  # The documented debugging window. A scan over an arbitrary window is not the
  # scan a retro completes, so it may not claim the reviews it read.
  run "$RETRO_SCAN" --home "$TMPDIR" --workbench "$TMPDIR/wb" --consume --since 7d
  [[ "$status" -eq 2 ]]
  [[ "$output" == *"cannot be combined"* ]]
  [[ ! -f "$RECORD" ]]
}

# ── The completion only honours its own scan ────────────────────────────────

@test "a record from another scan is refused and deletes nothing" {
  _make_review "other-branch-review"
  _write_record "aaaaaaaaaaaa" "other-branch-review"

  run "$RETRO_CONSUME" --scan-id "bbbbbbbbbbbb"
  [[ "$status" -eq 1 ]]
  [[ "$output" == *"belongs to scan aaaaaaaaaaaa"* ]]
  [[ -d "$REVIEWS/other-branch-review" ]]
}

@test "the refusal names otto-log so the stray record can be traced" {
  _make_review "other-branch-review"
  _write_record "aaaaaaaaaaaa" "other-branch-review"

  run "$RETRO_CONSUME" --scan-id "bbbbbbbbbbbb"
  [[ "$output" == *"otto-log show aaaaaaaaaaaa"* ]]
}

@test "a matching scan id deletes what that scan read" {
  _make_review "mine-self-branch"
  _write_record "cccccccccccc" "mine-self-branch"

  run "$RETRO_CONSUME" --scan-id "cccccccccccc"
  [[ "$status" -eq 0 ]]
  [[ ! -d "$REVIEWS/mine-self-branch" ]]
  [[ ! -f "$RECORD" ]]
}

@test "no record at all is not a failure" {
  run "$RETRO_CONSUME" --scan-id "cccccccccccc"
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"nothing to clean up"* ]]
}

@test "--dry-run reports what it would delete and deletes nothing" {
  _make_review "mine-self-branch"
  _write_record "cccccccccccc" "mine-self-branch"

  run "$RETRO_CONSUME" --scan-id "cccccccccccc" --dry-run
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"Would delete mine-self-branch"* ]]
  [[ -d "$REVIEWS/mine-self-branch" ]]
  [[ -f "$RECORD" ]]
}

@test "a missing scan id is refused rather than defaulting to delete" {
  _make_review "mine-self-branch"
  _write_record "cccccccccccc" "mine-self-branch"

  run "$RETRO_CONSUME"
  [[ "$status" -eq 2 ]]
  [[ -d "$REVIEWS/mine-self-branch" ]]
}

@test "only the reviews the record names are deleted" {
  _make_review "claimed-review"
  _make_review "unrelated-review"
  _write_record "cccccccccccc" "claimed-review"

  run "$RETRO_CONSUME" --scan-id "cccccccccccc"
  [[ "$status" -eq 0 ]]
  [[ ! -d "$REVIEWS/claimed-review" ]]
  [[ -d "$REVIEWS/unrelated-review" ]]
}

# ── retro-complete passes the ID through ────────────────────────────────────

@test "retro-complete without a scan id refuses before banking the window" {
  HOME="$TMPDIR/home" mkdir -p "$TMPDIR/home/.claude"

  HOME="$TMPDIR/home" run "$RETRO_COMPLETE"
  [[ "$status" -eq 2 ]]
  [[ "$output" == *"requires the scan ID"* ]]
  # The window is not banked by a completion that did not happen.
  [[ ! -f "$TMPDIR/home/.claude/.last-retro" ]]
}

@test "retro-complete does not bank the window when the record is refused" {
  mkdir -p "$TMPDIR/home/.claude"
  _make_review "other-branch-review"
  _write_record "aaaaaaaaaaaa" "other-branch-review"

  HOME="$TMPDIR/home" run "$RETRO_COMPLETE" "bbbbbbbbbbbb"
  [[ "$status" -ne 0 ]]
  [[ -d "$REVIEWS/other-branch-review" ]]
  [[ ! -f "$TMPDIR/home/.claude/.last-retro" ]]
}

@test "retro-complete banks the window once its own reviews are cleaned up" {
  mkdir -p "$TMPDIR/home/.claude"
  _make_review "mine-self-branch"
  _write_record "cccccccccccc" "mine-self-branch"

  HOME="$TMPDIR/home" run "$RETRO_COMPLETE" "cccccccccccc"
  [[ "$status" -eq 0 ]]
  [[ ! -d "$REVIEWS/mine-self-branch" ]]
  [[ -f "$TMPDIR/home/.claude/.last-retro" ]]
}
