#!/usr/bin/env bats
# Tests for retro-scan Python script — PR comment fetching and rule cross-referencing.

bats_require_minimum_version 1.5.0

setup() {
  load 'test_helper'
  common_setup
  TMPDIR="$(mktemp -d)"
  RETRO_SCAN="$REPO_ROOT/ai/claude/bin/retro-scan"
}

teardown() {
  rm -rf "$TMPDIR"
  common_teardown
}

_py() {
  python3 -c "
import sys, importlib.util, importlib.machinery
loader = importlib.machinery.SourceFileLoader('retro_scan', '$RETRO_SCAN')
spec = importlib.util.spec_from_loader('retro_scan', loader)
mod = importlib.util.module_from_spec(spec)
sys.modules['retro_scan'] = mod
spec.loader.exec_module(mod)
$1
"
}

_py_here() {
  local code
  code=$(cat)
  _py "$code"
}

_make_machine_md() {
  local home="$1"
  shift
  mkdir -p "$home/.claude/machine"
  cat > "$home/.claude/machine/machine.md" <<'HEADER'
<!-- last-updated: 2026-06-12 | generated by otto-workbench -->
# Machine Profile

## Project Registry

| Project | Path | Stack | Memory |
|---------|------|-------|--------|
HEADER
  for entry in "$@"; do
    echo "$entry" >> "$home/.claude/machine/machine.md"
  done
}

@test "retro-scan --help exits 0" {
  run "$RETRO_SCAN" --help
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"usage"* ]] || [[ "$output" == *"Usage"* ]]
}

@test "retro-scan --version prints version info" {
  run "$RETRO_SCAN" --version
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"retro-scan"* ]]
}

@test "parse_project_registry: extracts project paths from machine.md" {
  _make_machine_md "$TMPDIR" \
    "| myapp | /Users/test/git/myapp | Go | yes |" \
    "| infra | /Users/test/git/infra | bash | no |"

  result=$(_py_here <<PY
repos = mod.parse_project_registry("$TMPDIR/.claude/machine/machine.md")
for r in repos:
    print(r["name"], r["path"])
PY
)
  [[ "$result" == *"myapp"* ]]
  [[ "$result" == *"/Users/test/git/myapp"* ]]
  [[ "$result" == *"infra"* ]]
  [[ "$result" == *"/Users/test/git/infra"* ]]
}

@test "parse_project_registry: returns empty list for missing file" {
  result=$(_py 'print(len(mod.parse_project_registry("/nonexistent/machine.md")))')
  [[ "$result" == "0" ]]
}

@test "parse_project_registry: skips table header separator row" {
  _make_machine_md "$TMPDIR" \
    "| myapp | /Users/test/git/myapp | Go | yes |"

  result=$(_py_here <<PY
repos = mod.parse_project_registry("$TMPDIR/.claude/machine/machine.md")
print(len(repos))
PY
)
  [[ "$result" == "1" ]]
}

@test "resolve_github_remote: ssh remote" {
  result=$(_py 'print(mod.resolve_github_remote("git@github.com:otto-nation/myapp.git"))')
  [[ "$result" == "otto-nation/myapp" ]]
}

@test "resolve_github_remote: https remote" {
  result=$(_py 'print(mod.resolve_github_remote("https://github.com/otto-nation/myapp.git"))')
  [[ "$result" == "otto-nation/myapp" ]]
}

@test "resolve_github_remote: https without .git" {
  result=$(_py 'print(mod.resolve_github_remote("https://github.com/otto-nation/myapp"))')
  [[ "$result" == "otto-nation/myapp" ]]
}

@test "resolve_github_remote: non-github remote returns None" {
  result=$(_py 'print(mod.resolve_github_remote("git@gitlab.com:org/repo.git"))')
  [[ "$result" == "None" ]]
}

# ── is_noise ─────────────────────────────────────────────────────────────────

@test "is_noise: approvals are noise" {
  result=$(_py 'print(mod.is_noise("LGTM"))')
  [[ "$result" == "True" ]]
}

@test "is_noise: looks good is noise" {
  result=$(_py 'print(mod.is_noise("Looks good!"))')
  [[ "$result" == "True" ]]
}

@test "is_noise: thumbs up is noise" {
  result=$(_py 'print(mod.is_noise("+1"))')
  [[ "$result" == "True" ]]
}

@test "is_noise: substantive comment is not noise" {
  result=$(_py 'print(mod.is_noise("This should validate the redirect URI against an allowlist"))')
  [[ "$result" == "False" ]]
}

@test "is_noise: short nit-only is noise" {
  result=$(_py 'print(mod.is_noise("nit"))')
  [[ "$result" == "True" ]]
}

@test "is_noise: nit with detail is not noise" {
  result=$(_py 'print(mod.is_noise("nit: rename this to fooBar for consistency"))')
  [[ "$result" == "False" ]]
}

# ── parse_review_comment ─────────────────────────────────────────────────────

@test "parse_review_comment: extracts fields from API response" {
  result=$(_py_here <<'PY'
comment = {
    "user": {"login": "reviewer1"},
    "body": "This should validate the redirect URI",
    "path": "src/auth.go",
    "line": 45,
    "html_url": "https://github.com/org/repo/pull/1#discussion_r123"
}
parsed = mod.parse_review_comment(comment)
print(parsed["author"], parsed["path"], parsed["line"])
PY
)
  [[ "$result" == "reviewer1 src/auth.go 45" ]]
}

@test "parse_review_comment: handles missing path (general comment)" {
  result=$(_py_here <<'PY'
comment = {
    "user": {"login": "reviewer1"},
    "body": "Overall this looks good but consider X",
}
parsed = mod.parse_review_comment(comment)
print(parsed["path"], parsed["line"])
PY
)
  [[ "$result" == "None None" ]]
}

@test "parse_review_comment: truncates long bodies" {
  result=$(_py_here <<'PY'
comment = {
    "user": {"login": "r"},
    "body": "x" * 1000,
}
parsed = mod.parse_review_comment(comment)
print(len(parsed["body"]))
PY
)
  [[ "$result" -le 500 ]]
}

# Helper: create a rules directory with test rule files
_make_rules_dir() {
  local workbench="$1"
  local rules_dir="$workbench/ai/guidelines/rules"
  mkdir -p "$rules_dir"

  cat > "$rules_dir/security.md" <<'EOF'
# Security

## Secrets and Credentials

- Never write secrets, tokens, API keys, passwords, or credentials to any tracked file
- If you need to reference a secret in a script, read it from the environment
EOF

  cat > "$rules_dir/general.md" <<'EOF'
# General Coding Principles

## Code Quality

- Prefer solutions that work for the general case
- Always check existing tooling before adding anything new
- Never introduce changes that violate SSOT or DRY
EOF
}

# ── load_rules ───────────────────────────────────────────────────────────────

@test "load_rules: loads rules files from workbench" {
  _make_rules_dir "$TMPDIR/wb"

  result=$(_py_here <<PY
from pathlib import Path
rules = mod.load_rules(Path("$TMPDIR/wb"))
print(len(rules))
for r in rules:
    print(r["filename"])
PY
)
  [[ "$result" == *"2"* ]]
  [[ "$result" == *"security.md"* ]]
  [[ "$result" == *"general.md"* ]]
}

@test "load_rules: extracts keywords from rule text" {
  _make_rules_dir "$TMPDIR/wb"

  result=$(_py_here <<PY
from pathlib import Path
rules = mod.load_rules(Path("$TMPDIR/wb"))
sec = [r for r in rules if r["filename"] == "security.md"][0]
print("secrets" in sec["keywords"])
print("credentials" in sec["keywords"])
PY
)
  [[ "$result" == *"True"* ]]
  [[ "$result" != *"False"* ]]
}

@test "load_rules: returns empty list when dir missing" {
  result=$(_py_here <<PY
from pathlib import Path
rules = mod.load_rules(Path("/nonexistent/wb"))
print(len(rules))
PY
)
  [[ "$result" == "0" ]]
}

# ── find_nearest_rule ────────────────────────────────────────────────────────

@test "find_nearest_rule: matches security comment to security.md" {
  _make_rules_dir "$TMPDIR/wb"

  result=$(_py_here <<PY
from pathlib import Path
rules = mod.load_rules(Path("$TMPDIR/wb"))
match = mod.find_nearest_rule("This API key should not be hardcoded in the source", rules)
print(match["filename"] if match else "None")
PY
)
  [[ "$result" == "security.md" ]]
}

@test "find_nearest_rule: returns None for unrelated comment" {
  _make_rules_dir "$TMPDIR/wb"

  result=$(_py_here <<PY
from pathlib import Path
rules = mod.load_rules(Path("$TMPDIR/wb"))
match = mod.find_nearest_rule("the button color should be blue", rules)
print(match["filename"] if match else "None")
PY
)
  [[ "$result" == "None" ]]
}

# ── format_report ────────────────────────────────────────────────────────────

@test "format_report: produces markdown with repo sections" {
  result=$(_py_here <<'PY'
scan_data = {
    "repos": [
        {
            "github": "otto-nation/myapp",
            "prs": [
                {
                    "number": 42,
                    "title": "feat: add auth",
                    "merged_at": "2026-06-08",
                    "author": "isaac",
                    "comments": [
                        {
                            "author": "reviewer1",
                            "body": "Validate the redirect URI",
                            "path": "src/auth.go",
                            "line": 45,
                            "url": "",
                            "nearest_rule": {"filename": "security.md", "match_snippet": "Never write secrets"},
                            "direction": "received",
                        }
                    ],
                }
            ],
        }
    ],
    "rules_summary": [
        {"filename": "security.md", "matched": 1, "gaps": 0},
    ],
}
report = mod.format_report(scan_data)
print(report)
PY
)
  [[ "$result" == *"otto-nation/myapp"* ]]
  [[ "$result" == *"PR #42"* ]]
  [[ "$result" == *"Validate the redirect URI"* ]]
  [[ "$result" == *"security.md"* ]]
  [[ "$result" == *"Rules Coverage Summary"* ]]
}

@test "format_report: handles empty scan" {
  result=$(_py_here <<'PY'
scan_data = {"repos": [], "rules_summary": []}
report = mod.format_report(scan_data)
print(report)
PY
)
  [[ "$result" == *"Retro Scan Report"* ]]
  [[ "$result" == *"No PR comments found"* ]]
}

# ── Integration (with --home, offline) ────────────────────────────────────────

@test "retro-scan: runs with empty home, produces report header" {
  run "$RETRO_SCAN" --home "$TMPDIR"
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"Retro Scan Report"* ]]
}
