"""Shared fixtures for the retro suites.

`make_rules_dir` is the two-file corpus (`security.md`, `general.md`) the scan
and rules tests both load. `make_machine_md` writes a Project Registry the
scan tests parse. Not: the real workbench rule tree, which `retro_rules_test`
loads on its own.
"""

from pathlib import Path


def make_rules_dir(workbench: Path) -> Path:
    rules_dir = workbench / "ai" / "guidelines" / "rules"
    rules_dir.mkdir(parents=True)
    (rules_dir / "security.md").write_text(
        "# Security\n"
        "\n"
        "## Secrets and Credentials\n"
        "\n"
        "- Never write secrets, tokens, API keys, passwords, or credentials to any tracked file\n"
        "- If you need to reference a secret in a script, read it from the environment\n"
    )
    (rules_dir / "general.md").write_text(
        "# General Coding Principles\n"
        "\n"
        "## Code Quality\n"
        "\n"
        "- Prefer solutions that work for the general case\n"
        "- Always check existing tooling before adding anything new\n"
        "- Never introduce changes that violate SSOT or DRY\n"
    )
    return rules_dir


def make_machine_md(home: Path, *rows: str) -> Path:
    machine = home / ".claude" / "machine"
    machine.mkdir(parents=True)
    path = machine / "machine.md"
    body = (
        "<!-- last-updated: 2026-06-12 | generated by otto-workbench -->\n"
        "# Machine Profile\n"
        "\n"
        "## Project Registry\n"
        "\n"
        "| Project | Path | Stack | Memory |\n"
        "|---------|------|-------|--------|\n"
    )
    if rows:
        body += "\n".join(rows) + "\n"
    path.write_text(body)
    return path
