#!/usr/bin/env bats
# Tests for the retro-scan CLI. In-process cases live in the pytest suites
# named in tests/retro_scan_test.py, tests/retro_github_test.py,
# tests/retro_rules_test.py, tests/retro_report_test.py and
# tests/retro_reviews_test.py.

bats_require_minimum_version 1.5.0

setup() {
  load 'test_helper'
  common_setup
  RETRO_SCAN="$REPO_ROOT/ai/bin/retro-scan"
  sandbox_state_dir
}

teardown() {
  common_teardown
}

_make_machine_md() {
  local home="$1"
  shift
  mkdir -p "$home/.claude/machine"
  cat > "$home/.claude/machine/machine.md" <<'HEADER'
<!-- last-updated: 2026-06-12 | generated by otto-workbench -->
# Machine Profile

## Project Registry

| Project | Path | Stack | Memory |
|---------|------|-------|--------|
HEADER
  for entry in "$@"; do
    echo "$entry" >> "$home/.claude/machine/machine.md"
  done
}

@test "retro-scan --help exits 0" {
  run "$RETRO_SCAN" --help
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"usage"* ]] || [[ "$output" == *"Usage"* ]]
}

@test "retro-scan --version prints version info" {
  run "$RETRO_SCAN" --version
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"retro-scan"* ]]
}

# ── Integration (with --home, offline) ────────────────────────────────────────

@test "retro-scan: an empty registry refuses the run rather than banking it" {
  # No machine.md at all resolves to zero projects, which resolves to zero
  # repos — the same "resolves to nothing" case as a registry whose paths
  # are all broken, and it must be refused the same way.
  run "$RETRO_SCAN" --home "$TMPDIR"
  [[ "$status" -eq 1 ]]
  [[ "$output" == *"Refusing to bank a scan window"* ]]
  [[ "$output" != *"Retro Scan Report"* ]]
}

@test "retro-scan: an empty registry is named as such, not as 0 projects resolving" {
  # The two no-repo faults need different remedies, so they must not share a
  # message: "none of the 0 registered projects resolved" names neither.
  run "$RETRO_SCAN" --home "$TMPDIR"
  [[ "$status" -eq 1 ]]
  [[ "$output" == *"lists no projects"* ]]
  [[ "$output" != *"none of the 0"* ]]
}

@test "retro-scan: a registry that resolves to no GitHub repo fails the run" {
  # Banking the scan window here would stamp the retro cooldown and delete the
  # consumed local reviews, closing the window over PR feedback never read.
  _make_machine_md "$TMPDIR" \
    "| myapp | $TMPDIR/absent | Go | yes |"

  run "$RETRO_SCAN" --home "$TMPDIR"
  [[ "$status" -eq 1 ]]
  [[ "$output" == *"none of the 1 registered projects"* ]]
  [[ "$output" == *"Project Registry paths"* ]]
  [[ "$output" != *"Retro Scan Report"* ]]
}

@test "retro-scan: one resolving repo is enough to proceed" {
  mkdir -p "$TMPDIR/good"
  git -C "$TMPDIR/good" init -q
  git -C "$TMPDIR/good" remote add origin git@github.com:otto-nation/myapp.git
  _make_machine_md "$TMPDIR" \
    "| myapp | $TMPDIR/good | Go | yes |" \
    "| absent | $TMPDIR/absent | Go | no |"

  run "$RETRO_SCAN" --home "$TMPDIR" --since 1m
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"Retro Scan Report"* ]]
}
