#!/usr/bin/env bats
# Tests for retro-scan Python script — PR comment fetching and rule cross-referencing.

bats_require_minimum_version 1.5.0

setup() {
  load 'test_helper'
  common_setup
  TMPDIR="$(mktemp -d)"
  RETRO_SCAN="$REPO_ROOT/ai/claude/bin/retro-scan"
}

teardown() {
  rm -rf "$TMPDIR"
  common_teardown
}

_py() {
  python3 -c "
import sys, importlib.util, importlib.machinery
loader = importlib.machinery.SourceFileLoader('retro_scan', '$RETRO_SCAN')
spec = importlib.util.spec_from_loader('retro_scan', loader)
mod = importlib.util.module_from_spec(spec)
sys.modules['retro_scan'] = mod
spec.loader.exec_module(mod)
$1
"
}

_py_here() {
  local code
  code=$(cat)
  _py "$code"
}

_make_machine_md() {
  local home="$1"
  shift
  mkdir -p "$home/.claude/machine"
  cat > "$home/.claude/machine/machine.md" <<'HEADER'
<!-- last-updated: 2026-06-12 | generated by otto-workbench -->
# Machine Profile

## Project Registry

| Project | Path | Stack | Memory |
|---------|------|-------|--------|
HEADER
  for entry in "$@"; do
    echo "$entry" >> "$home/.claude/machine/machine.md"
  done
}

@test "retro-scan --help exits 0" {
  run "$RETRO_SCAN" --help
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"usage"* ]] || [[ "$output" == *"Usage"* ]]
}

@test "retro-scan --version prints version info" {
  run "$RETRO_SCAN" --version
  [[ "$status" -eq 0 ]]
  [[ "$output" == *"retro-scan"* ]]
}

@test "parse_project_registry: extracts project paths from machine.md" {
  _make_machine_md "$TMPDIR" \
    "| myapp | /Users/test/git/myapp | Go | yes |" \
    "| infra | /Users/test/git/infra | bash | no |"

  result=$(_py_here <<PY
repos = mod.parse_project_registry("$TMPDIR/.claude/machine/machine.md")
for r in repos:
    print(r["name"], r["path"])
PY
)
  [[ "$result" == *"myapp"* ]]
  [[ "$result" == *"/Users/test/git/myapp"* ]]
  [[ "$result" == *"infra"* ]]
  [[ "$result" == *"/Users/test/git/infra"* ]]
}

@test "parse_project_registry: returns empty list for missing file" {
  result=$(_py 'print(len(mod.parse_project_registry("/nonexistent/machine.md")))')
  [[ "$result" == "0" ]]
}

@test "parse_project_registry: skips table header separator row" {
  _make_machine_md "$TMPDIR" \
    "| myapp | /Users/test/git/myapp | Go | yes |"

  result=$(_py_here <<PY
repos = mod.parse_project_registry("$TMPDIR/.claude/machine/machine.md")
print(len(repos))
PY
)
  [[ "$result" == "1" ]]
}

@test "resolve_github_remote: ssh remote" {
  result=$(_py 'print(mod.resolve_github_remote("git@github.com:otto-nation/myapp.git"))')
  [[ "$result" == "otto-nation/myapp" ]]
}

@test "resolve_github_remote: https remote" {
  result=$(_py 'print(mod.resolve_github_remote("https://github.com/otto-nation/myapp.git"))')
  [[ "$result" == "otto-nation/myapp" ]]
}

@test "resolve_github_remote: https without .git" {
  result=$(_py 'print(mod.resolve_github_remote("https://github.com/otto-nation/myapp"))')
  [[ "$result" == "otto-nation/myapp" ]]
}

@test "resolve_github_remote: non-github remote returns None" {
  result=$(_py 'print(mod.resolve_github_remote("git@gitlab.com:org/repo.git"))')
  [[ "$result" == "None" ]]
}

# ── is_noise ─────────────────────────────────────────────────────────────────

@test "is_noise: approvals are noise" {
  result=$(_py 'print(mod.is_noise("LGTM"))')
  [[ "$result" == "True" ]]
}

@test "is_noise: looks good is noise" {
  result=$(_py 'print(mod.is_noise("Looks good!"))')
  [[ "$result" == "True" ]]
}

@test "is_noise: thumbs up is noise" {
  result=$(_py 'print(mod.is_noise("+1"))')
  [[ "$result" == "True" ]]
}

@test "is_noise: substantive comment is not noise" {
  result=$(_py 'print(mod.is_noise("This should validate the redirect URI against an allowlist"))')
  [[ "$result" == "False" ]]
}

@test "is_noise: short nit-only is noise" {
  result=$(_py 'print(mod.is_noise("nit"))')
  [[ "$result" == "True" ]]
}

@test "is_noise: nit with detail is not noise" {
  result=$(_py 'print(mod.is_noise("nit: rename this to fooBar for consistency"))')
  [[ "$result" == "False" ]]
}

# ── parse_review_comment ─────────────────────────────────────────────────────

@test "parse_review_comment: extracts fields from API response" {
  result=$(_py_here <<'PY'
comment = {
    "user": {"login": "reviewer1"},
    "body": "This should validate the redirect URI",
    "path": "src/auth.go",
    "line": 45,
    "html_url": "https://github.com/org/repo/pull/1#discussion_r123"
}
parsed = mod.parse_review_comment(comment)
print(parsed["author"], parsed["path"], parsed["line"])
PY
)
  [[ "$result" == "reviewer1 src/auth.go 45" ]]
}

@test "parse_review_comment: handles missing path (general comment)" {
  result=$(_py_here <<'PY'
comment = {
    "user": {"login": "reviewer1"},
    "body": "Overall this looks good but consider X",
}
parsed = mod.parse_review_comment(comment)
print(parsed["path"], parsed["line"])
PY
)
  [[ "$result" == "None None" ]]
}

@test "parse_review_comment: truncates long bodies" {
  result=$(_py_here <<'PY'
comment = {
    "user": {"login": "r"},
    "body": "x" * 1000,
}
parsed = mod.parse_review_comment(comment)
print(len(parsed["body"]))
PY
)
  [[ "$result" -le 500 ]]
}
