"""Layer 2 — knowledge base store. May import: core."""

from .create import (
    ArticleNotFoundError,
    ArticleReferencedError,
    WikiExistsError,
    append_log,
    archive_article,
    clean_source_type,
    init_wiki,
    manifest_row,
    slugify_title,
    stage_source,
)
from .model import Article, Source, Wiki
from .paths import (
    ARCHIVE_DIR,
    ARTICLES_DIR,
    DEFAULT_SETTINGS,
    DEFAULT_WIKI_DIRNAME,
    DRAFTS_DIR,
    INDEX_FILE,
    LOG_FILE,
    MAX_PARENT_DEPTH,
    META_DIR,
    RAW_DIR,
    SCHEMA_FILE,
    SOURCES_FILE,
    find_wiki,
    is_wiki,
)
from .parsing import HASH_PREFIX_LEN, gap_tokens, hash_file, parse_query_gap, read_text
from .report import build_index, collect_lint, collect_signals, collect_status

__all__ = [
    "ARCHIVE_DIR",
    "ARTICLES_DIR",
    "Article",
    "ArticleNotFoundError",
    "ArticleReferencedError",
    "DEFAULT_SETTINGS",
    "DEFAULT_WIKI_DIRNAME",
    "DRAFTS_DIR",
    "HASH_PREFIX_LEN",
    "INDEX_FILE",
    "LOG_FILE",
    "MAX_PARENT_DEPTH",
    "META_DIR",
    "RAW_DIR",
    "SCHEMA_FILE",
    "SOURCES_FILE",
    "Source",
    "Wiki",
    "WikiExistsError",
    "append_log",
    "archive_article",
    "build_index",
    "clean_source_type",
    "collect_lint",
    "collect_signals",
    "collect_status",
    "find_wiki",
    "gap_tokens",
    "hash_file",
    "init_wiki",
    "is_wiki",
    "manifest_row",
    "parse_query_gap",
    "read_text",
    "slugify_title",
    "stage_source",
]
